import analyze from '../src/analyzer.js'
import * as core from '../src/core.js'
import generate from '../src/generator.js'
import parse from '../src/parser.js'

const PREAMBLE = `// Generated by the Fling compiler
// Do not edit by hand
function display(x) { console.log(x); }
function size(col) { return col.length; }
const __unitFactors = { grams: 1, kg: 1000, oz: 28.35, lbs: 453.59, ml: 1, liters: 1000, cups: 236.6, tbsp: 14.79, tsp: 4.93, floz: 29.57, celsius: 1, seconds: 1, minutes: 60, hours: 3600 };
function convert(val, unit) {
  if (unit === "fahrenheit") return val * 9 / 5 + 32;
  return val / __unitFactors[unit];
}
function mix(a, b) {}`

function js(source) {
  return generate(analyze(parse(source)))
}

function expectValidJavaScript(output) {
  expect(() => new Function(output)).not.toThrow()
}

const successfulExamples = [
  [
    'hello world',
    String.raw`-- hello.fling
ingredient greeting: label = "Hello from Fling!"
serve greeting`,
  ],
  [
    'simple addition',
    String.raw`-- simple_add.fling
ingredient x: count = 5
ingredient y: count = 3
ingredient result: count = x + y
serve result`,
  ],
  [
    'unit addition',
    String.raw`-- unit_add.fling
ingredient flour: grams = 200g
ingredient extra: grams = 100g
ingredient total = flour + extra
serve total`,
  ],
  [
    'full recipe',
    String.raw`-- bread.fling

prep Dough:
  flour: grams
  water: ml
  salt: grams
  yeast: grams

recipe make_dough(flour: grams, water: ml) yields Dough:
  ingredient d = Dough { flour: flour, water: water, salt: 9g, yeast: 7g }
  serve d

recipe bake(temp: celsius, duration: minutes) yields label:
  taste temp > 250celsius:
    serve "too hot!"
  otherwise:
    serve "baking..."

ingredient my_dough = make_dough(500g, 350ml)
step show: display(my_dough.flour)`,
  ],
  [
    'loop example',
    String.raw`-- countdown.fling
stirring ingredient count: count = 10

simmer count > 0:
  step show: display(count)
  step decrement: count = count - 1`,
  ],
  [
    'collection example',
    String.raw`-- ingredients_list.fling
ingredient items: [label] = ["flour", "water", "salt", "yeast"]

batch item in items:
  step show: display(item)`,
  ],
  [
    'scaling recipe',
    String.raw`-- scaling.fling
recipe scale_recipe(flour: grams, factor: count) yields grams:
  ingredient scaled = flour * factor
  serve scaled

ingredient base: grams = 500g
ingredient double = scale_recipe(base, 2)
serve double`,
  ],
]

describe('the generator', () => {
  test.each(successfulExamples)(
    'generates valid JavaScript for the Section 12 %s example',
    (_name, source) => {
      expectValidJavaScript(js(source))
    },
  )

  test.each([
    [
      'intentional unit mismatch',
      String.raw`ingredient flour: grams = 200g
ingredient milk: ml = 350ml
ingredient bad = flour + milk`,
      TypeError,
    ],
    [
      'intentional missing serve',
      String.raw`recipe compute(x: count) yields count:
  ingredient y = x + 1`,
      Error,
    ],
  ])('does not generate after the Section 12 %s analyzer error', (_name, source, error) => {
    expect(() => analyze(parse(source))).toThrow(error)
  })

  test('emits the preamble in every output', () => {
    expect(js(`ingredient x: count = 1`).startsWith(PREAMBLE)).toBe(true)
  })

  test('PrepDecl generates no output after the preamble', () => {
    expect(
      js(String.raw`prep Dough:
  flour: grams`),
    ).toBe(PREAMBLE)
  })

  test('UnitLit generates a plain number', () => {
    expect(js(`ingredient flour: grams = 200g`)).toContain('const flour = 200;')
  })

  test('UnitLit generates the base-unit runtime value', () => {
    expect(js(`ingredient flour: grams = 1kg`)).toContain('const flour = 1000;')
  })

  test('convert generates an explicit runtime conversion to the target unit', () => {
    expect(js(`ingredient flour: kg = convert(1000g, "kg")`)).toContain(
      'const flour = convert(1000, "kg");',
    )
  })

  test('BoolLit yes generates true and no generates false', () => {
    const output = js(String.raw`ingredient ready: truth = yes
ingredient burned: truth = no`)

    expect(output).toContain('const ready = true;')
    expect(output).toContain('const burned = false;')
  })

  test('StructLit generates a JS object', () => {
    const output = js(String.raw`prep Dough:
  flour: grams
ingredient d = Dough { flour: 200g }`)

    expect(output).toContain('const d = ({ flour: 200 });')
  })

  test('RecipeDecl generates a JS function', () => {
    const output = js(String.raw`recipe add(x: count, y: count) yields count:
  serve x + y`)

    expect(output).toContain(`function add(x, y) {
  return (x + y);
}`)
  })

  test('TasteStmt generates an if statement', () => {
    const output = js(String.raw`recipe check(hot: truth) yields nothing:
  taste hot:
    step show: display("hot")
  otherwise:
    step show: display("fine")`)

    expect(output).toContain(`  if (hot) {
    display("hot");
  }
  else {
    display("fine");
  }`)
  })

  test('TasteStmt without otherwise generates only an if statement', () => {
    const output = js(String.raw`recipe check(hot: truth) yields nothing:
  taste hot:
    step show: display("hot")`)

    expect(output).toContain(`  if (hot) {
    display("hot");
  }`)
    expect(output).not.toContain('else')
  })

  test('SimmerStmt generates a while loop', () => {
    const output = js(String.raw`stirring ingredient count: count = 1
simmer count > 0:
  step decrement: count = count - 1`)

    expect(output).toContain(`while ((count > 0)) {
  count = (count - 1);
}`)
  })

  test('BatchStmt generates a for-of loop', () => {
    const output = js(String.raw`ingredient items: [count] = [1, 2]
batch item in items:
  step show: display(item)`)

    expect(output).toContain(`for (const item of items) {
  display(item);
}`)
  })

  test('TossStmt generates break', () => {
    expect(
      js(String.raw`ingredient items: [count] = [1]
batch item in items:
  toss`),
    ).toContain('break;')
  })

  test('SkipStmt generates continue', () => {
    expect(
      js(String.raw`ingredient items: [count] = [1]
batch item in items:
  skip`),
    ).toContain('continue;')
  })

  test('SpoiledStmt generates throw new Error', () => {
    expect(js(`spoiled "too salty"`)).toContain('throw new Error("too salty");')
  })

  test('empty program generates just the preamble', () => {
    expect(generate(new core.Program([]))).toBe(PREAMBLE)
  })

  test('string pseudo-nodes generate empty output', () => {
    expect(generate(new core.Program(['-- parsed comment placeholder']))).toBe(PREAMBLE)
  })

  test('PantryDecl generates no output after the preamble', () => {
    expect(js('pantry "std.fling"')).toBe(PREAMBLE)
  })

  test('bare serve inside a recipe generates return without value', () => {
    const output = js(String.raw`recipe stop() yields nothing:
  serve`)

    expect(output).toContain(`function stop() {
  return;
}`)
  })

  test('top-level bare serve generates no output after the preamble', () => {
    expect(generate(new core.Program([new core.ServeStmt(null)]))).toBe(PREAMBLE)
  })

  test('UnaryExp with negate operator generates JavaScript negation', () => {
    expect(js('ingredient x: count = -1')).toContain('const x = (-1);')
  })

  test('UnaryExp with not operator generates JavaScript negation', () => {
    expect(js('ingredient x: truth = not no')).toContain('const x = (!false);')
  })

  test('unknown UnaryExp operators are rejected', () => {
    expect(() =>
      generate(
        new core.Program([
          new core.IngredientDecl(
            'x',
            new core.PrimitiveType('count'),
            new core.UnaryExp('sqrt', new core.IntLit(4)),
            false,
          ),
        ]),
      ),
    ).toThrow(/unknown node UnaryExp/)
  })

  test('nested expressions preserve precedence with parentheses', () => {
    const output = js('ingredient x: count = (1 + 2) * (3 - 4)')

    expect(output).toContain('const x = ((1 + 2) * (3 - 4));')
  })

  test('truth operators generate JavaScript boolean operators', () => {
    const output = js('ingredient ok: truth = yes and no or yes')

    expect(output).toContain('const ok = ((true && false) || true);')
  })

  test('equality operators generate strict JavaScript comparisons', () => {
    const output = js(String.raw`ingredient same: truth = 1 == 1
ingredient different: truth = 1 != 2`)

    expect(output).toContain('const same = (1 === 1);')
    expect(output).toContain('const different = (1 !== 2);')
  })

  test('float literal generation preserves decimal values', () => {
    expect(js('ingredient x: amount = 1.5')).toContain('const x = 1.5;')
  })

  test('assignment expression generation emits target assignment', () => {
    const output = js(String.raw`stirring ingredient x: count = 1
step change: x = 2`)

    expect(output).toContain('x = 2;')
  })

  test('IndexAccessExp generation emits bracket access', () => {
    const output = js(String.raw`ingredient xs: [count] = [1, 2]
ingredient first: count = xs[0]`)

    expect(output).toContain('const first = xs[0];')
  })

  test('throws on unknown node types', () => {
    class UnknownNode {}

    expect(() => generate(new core.Program([new UnknownNode()]))).toThrow(
      /unknown node UnknownNode/,
    )
  })
})
