import analyze from "../src/analyzer.js"
import generate from "../src/generator.js"
import parse from "../src/parser.js"

const PREAMBLE = `// Generated by the Fling compiler
// Do not edit by hand
function display(x) { console.log(x); }
function size(col) { return col.length; }
function convert(val, unit) { return val; }
function mix(a, b) {}`

function js(source) {
  return generate(analyze(parse(source)))
}

function expectValidJavaScript(output) {
  expect(() => new Function(output)).not.toThrow()
}

const successfulExamples = [
  [
    "hello world",
    String.raw`-- hello.fling
ingredient greeting: label = "Hello from Fling!"
serve greeting`,
  ],
  [
    "simple addition",
    String.raw`-- simple_add.fling
ingredient x: count = 5
ingredient y: count = 3
ingredient result: count = x + y
serve result`,
  ],
  [
    "unit addition",
    String.raw`-- unit_add.fling
ingredient flour: grams = 200g
ingredient extra: grams = 100g
ingredient total = flour + extra
serve total`,
  ],
  [
    "full recipe",
    String.raw`-- bread.fling

prep Dough:
  flour: grams
  water: ml
  salt: grams
  yeast: grams

recipe make_dough(flour: grams, water: ml) yields Dough:
  ingredient d = Dough { flour: flour, water: water, salt: 9g, yeast: 7g }
  serve d

recipe bake(temp: celsius, duration: minutes) yields label:
  taste temp > 250celsius:
    serve "too hot!"
  otherwise:
    serve "baking..."

ingredient my_dough = make_dough(500g, 350ml)
step show: display(my_dough.flour)`,
  ],
  [
    "loop example",
    String.raw`-- countdown.fling
stirring ingredient count: count = 10

simmer count > 0:
  step show: display(count)
  step decrement: count = count - 1`,
  ],
  [
    "collection example",
    String.raw`-- ingredients_list.fling
ingredient items: [label] = ["flour", "water", "salt", "yeast"]

batch item in items:
  step show: display(item)`,
  ],
  [
    "scaling recipe",
    String.raw`-- scaling.fling
recipe scale_recipe(flour: grams, factor: count) yields grams:
  ingredient scaled = flour * factor
  serve scaled

ingredient base: grams = 500g
ingredient double = scale_recipe(base, 2)
serve double`,
  ],
]

describe("the generator", () => {
  test.each(successfulExamples)(
    "generates valid JavaScript for the Section 12 %s example",
    (_name, source) => {
      expectValidJavaScript(js(source))
    }
  )

  test.each([
    [
      "intentional unit mismatch",
      String.raw`ingredient flour: grams = 200g
ingredient milk: ml = 350ml
ingredient bad = flour + milk`,
      TypeError,
    ],
    [
      "intentional missing serve",
      String.raw`recipe compute(x: count) yields count:
  ingredient y = x + 1`,
      Error,
    ],
  ])("does not generate after the Section 12 %s analyzer error", (_name, source, error) => {
    expect(() => analyze(parse(source))).toThrow(error)
  })

  test("emits the preamble in every output", () => {
    expect(js(`ingredient x: count = 1`).startsWith(PREAMBLE)).toBe(true)
  })

  test("PrepDecl generates no output after the preamble", () => {
    expect(
      js(String.raw`prep Dough:
  flour: grams`)
    ).toBe(PREAMBLE)
  })

  test("UnitLit generates a plain number", () => {
    expect(js(`ingredient flour: grams = 200g`)).toContain("const flour = 200;")
  })

  test("BoolLit yes generates true and no generates false", () => {
    const output = js(String.raw`ingredient ready: truth = yes
ingredient burned: truth = no`)

    expect(output).toContain("const ready = true;")
    expect(output).toContain("const burned = false;")
  })

  test("StructLit generates a JS object", () => {
    const output = js(String.raw`prep Dough:
  flour: grams
ingredient d = Dough { flour: 200g }`)

    expect(output).toContain("const d = ({ flour: 200 });")
  })

  test("RecipeDecl generates a JS function", () => {
    const output = js(String.raw`recipe add(x: count, y: count) yields count:
  serve x + y`)

    expect(output).toContain(`function add(x, y) {
  return (x + y);
}`)
  })

  test("TasteStmt generates an if statement", () => {
    const output = js(String.raw`recipe check(hot: truth) yields nothing:
  taste hot:
    step show: display("hot")
  otherwise:
    step show: display("fine")`)

    expect(output).toContain(`  if (hot) {
    display("hot");
  }
  else {
    display("fine");
  }`)
  })

  test("SimmerStmt generates a while loop", () => {
    const output = js(String.raw`stirring ingredient count: count = 1
simmer count > 0:
  step decrement: count = count - 1`)

    expect(output).toContain(`while ((count > 0)) {
  count = (count - 1);
}`)
  })

  test("BatchStmt generates a for-of loop", () => {
    const output = js(String.raw`ingredient items: [count] = [1, 2]
batch item in items:
  step show: display(item)`)

    expect(output).toContain(`for (const item of items) {
  display(item);
}`)
  })

  test("TossStmt generates break", () => {
    expect(
      js(String.raw`ingredient items: [count] = [1]
batch item in items:
  toss`)
    ).toContain("break;")
  })

  test("SkipStmt generates continue", () => {
    expect(
      js(String.raw`ingredient items: [count] = [1]
batch item in items:
  skip`)
    ).toContain("continue;")
  })

  test("SpoiledStmt generates throw new Error", () => {
    expect(js(`spoiled "too salty"`)).toContain('throw new Error("too salty");')
  })
})
