import * as core from './core.js'

const PREAMBLE = `// Generated by the Fling compiler
// Do not edit by hand
function display(x) { console.log(x); }
function size(col) { return col.length; }
const __unitFactors = { grams: 1, kg: 1000, oz: 28.35, lbs: 453.59, ml: 1, liters: 1000, cups: 236.6, tbsp: 14.79, tsp: 4.93, floz: 29.57, celsius: 1, seconds: 1, minutes: 60, hours: 3600 };
function convert(val, unit) {
  if (unit === "fahrenheit") return val * 9 / 5 + 32;
  return val / __unitFactors[unit];
}
function mix(a, b) {}`

const UNIT_ALIASES = {
  g: 'grams',
}

const TO_BASE = {
  grams: 1,
  kg: 1000,
  oz: 28.35,
  lbs: 453.59,
  ml: 1,
  liters: 1000,
  cups: 236.6,
  tbsp: 14.79,
  tsp: 4.93,
  floz: 29.57,
  celsius: 1,
  fahrenheit: null,
  seconds: 1,
  minutes: 60,
  hours: 3600,
}

function normalizedUnit(unit) {
  return UNIT_ALIASES[unit] ?? unit
}

function unitValueInBase(value, unit) {
  const normalized = normalizedUnit(unit)
  if (normalized === 'fahrenheit') {
    return ((value - 32) * 5) / 9
  }
  return value * TO_BASE[normalized]
}

export default function generate(program) {
  function indentation(level) {
    return '  '.repeat(level)
  }

  function genBlock(statements, indent, topLevel) {
    return statements
      .map((statement) => gen(statement, indent, topLevel))
      .filter((line) => line.length > 0)
      .join('\n')
  }

  function gen(node, indent = 0, topLevel = true) {
    if (typeof node === 'string') {
      return ''
    }
    if (node instanceof core.Program) {
      const body = genBlock(node.statements, indent, true)
      return body ? `${PREAMBLE}\n${body}` : PREAMBLE
    }
    if (node instanceof core.PrepDecl) {
      return ''
    }
    if (node instanceof core.PantryDecl) {
      return ''
    }
    if (node instanceof core.RecipeDecl) {
      const params = node.params.map((param) => param.name).join(', ')
      const body = genBlock(node.body, indent + 1, false)
      return [
        `${indentation(indent)}function ${node.name}(${params}) {`,
        body,
        `${indentation(indent)}}`,
      ]
        .filter((line) => line.length > 0)
        .join('\n')
    }
    if (node instanceof core.IngredientDecl) {
      const keyword = node.mutable ? 'let' : 'const'
      return `${indentation(indent)}${keyword} ${node.name} = ${gen(node.initializer)};`
    }
    if (node instanceof core.StepStmt) {
      return `${indentation(indent)}${gen(node.expression)};`
    }
    if (node instanceof core.ServeStmt) {
      if (topLevel) {
        return node.expression ? `${indentation(indent)}console.log(${gen(node.expression)});` : ''
      }
      return node.expression
        ? `${indentation(indent)}return ${gen(node.expression)};`
        : `${indentation(indent)}return;`
    }
    if (node instanceof core.TasteStmt) {
      const consequent = genBlock(node.consequent, indent + 1, topLevel)
      const lines = [
        `${indentation(indent)}if (${gen(node.condition)}) {`,
        consequent,
        `${indentation(indent)}}`,
      ]
      if (node.alternate) {
        lines.push(`${indentation(indent)}else {`)
        lines.push(genBlock(node.alternate, indent + 1, topLevel))
        lines.push(`${indentation(indent)}}`)
      }
      return lines.filter((line) => line.length > 0).join('\n')
    }
    if (node instanceof core.SimmerStmt) {
      const body = genBlock(node.body, indent + 1, topLevel)
      return [
        `${indentation(indent)}while (${gen(node.condition)}) {`,
        body,
        `${indentation(indent)}}`,
      ]
        .filter((line) => line.length > 0)
        .join('\n')
    }
    if (node instanceof core.BatchStmt) {
      const body = genBlock(node.body, indent + 1, topLevel)
      return [
        `${indentation(indent)}for (const ${node.varName} of ${gen(node.collection)}) {`,
        body,
        `${indentation(indent)}}`,
      ]
        .filter((line) => line.length > 0)
        .join('\n')
    }
    if (node instanceof core.TossStmt) {
      return `${indentation(indent)}break;`
    }
    if (node instanceof core.SkipStmt) {
      return `${indentation(indent)}continue;`
    }
    if (node instanceof core.SpoiledStmt) {
      return `${indentation(indent)}throw new Error(${gen(node.message)});`
    }
    if (node instanceof core.BinaryExp) {
      if (node.op === 'and') {
        return `(${gen(node.left)} && ${gen(node.right)})`
      }
      if (node.op === 'or') {
        return `(${gen(node.left)} || ${gen(node.right)})`
      }
      if (node.op === '==') {
        return `(${gen(node.left)} === ${gen(node.right)})`
      }
      if (node.op === '!=') {
        return `(${gen(node.left)} !== ${gen(node.right)})`
      }
      return `(${gen(node.left)} ${node.op} ${gen(node.right)})`
    }
    if (node instanceof core.Assignment) {
      return `${gen(node.target)} = ${gen(node.source)}`
    }
    if (node instanceof core.UnaryExp) {
      if (node.op === 'not') {
        return `(!${gen(node.operand)})`
      }
      if (node.op === '-') {
        return `(-${gen(node.operand)})`
      }
    }
    if (node instanceof core.CallExp) {
      if (node.callee instanceof core.IdRef && node.callee.name === 'convert') {
        return `convert(${gen(node.args[0])}, ${JSON.stringify(node.args[1].unit)})`
      }
      return `${gen(node.callee)}(${node.args.map((arg) => gen(arg)).join(', ')})`
    }
    if (node instanceof core.FieldAccessExp) {
      return `${gen(node.object)}.${node.field}`
    }
    if (node instanceof core.IndexAccessExp) {
      return `${gen(node.collection)}[${gen(node.index)}]`
    }
    if (node instanceof core.StructLit) {
      const fields = node.fields.map((field) => `${field.name}: ${gen(field.value)}`).join(', ')
      return `({ ${fields} })`
    }
    if (node instanceof core.CollectionLit) {
      return `[${node.elements.map((element) => gen(element)).join(', ')}]`
    }
    if (node instanceof core.UnitLit) {
      return String(unitValueInBase(node.value, node.unit))
    }
    if (node instanceof core.IntLit) {
      return String(node.value)
    }
    if (node instanceof core.FloatLit) {
      return String(node.value)
    }
    if (node instanceof core.StringLit) {
      return JSON.stringify(node.value)
    }
    if (node instanceof core.BoolLit) {
      return node.value ? 'true' : 'false'
    }
    if (node instanceof core.IdRef) {
      return node.name
    }
    throw new TypeError(`unknown node ${node.constructor.name}`)
  }

  return gen(program)
}
