import * as core from "./core.js"

const PREAMBLE = `// Generated by the Fling compiler
// Do not edit by hand
function display(x) { console.log(x); }
function size(col) { return col.length; }
function convert(val, unit) { return val; }
function mix(a, b) {}`

export default function generate(program) {
  function indentation(level) {
    return "  ".repeat(level)
  }

  function genBlock(statements, indent, topLevel) {
    return statements
      .map((statement) => gen(statement, indent, topLevel))
      .filter((line) => line.length > 0)
      .join("\n")
  }

  function gen(node, indent = 0, topLevel = true) {
    if (typeof node === "string") {
      return ""
    }
    if (node instanceof core.Program) {
      const body = genBlock(node.statements, indent, true)
      return body ? `${PREAMBLE}\n${body}` : PREAMBLE
    }
    if (node instanceof core.PrepDecl) {
      return ""
    }
    if (node instanceof core.PantryDecl) {
      return ""
    }
    if (node instanceof core.RecipeDecl) {
      const params = node.params.map((param) => param.name).join(", ")
      const body = genBlock(node.body, indent + 1, false)
      return [
        `${indentation(indent)}function ${node.name}(${params}) {`,
        body,
        `${indentation(indent)}}`,
      ]
        .filter((line) => line.length > 0)
        .join("\n")
    }
    if (node instanceof core.IngredientDecl) {
      const keyword = node.mutable ? "let" : "const"
      return `${indentation(indent)}${keyword} ${node.name} = ${gen(node.initializer)};`
    }
    if (node instanceof core.StepStmt) {
      return `${indentation(indent)}${gen(node.expression)};`
    }
    if (node instanceof core.ServeStmt) {
      if (topLevel) {
        return node.expression
          ? `${indentation(indent)}console.log(${gen(node.expression)});`
          : ""
      }
      return node.expression
        ? `${indentation(indent)}return ${gen(node.expression)};`
        : `${indentation(indent)}return;`
    }
    if (node instanceof core.TasteStmt) {
      const consequent = genBlock(node.consequent, indent + 1, topLevel)
      const lines = [
        `${indentation(indent)}if (${gen(node.condition)}) {`,
        consequent,
        `${indentation(indent)}}`,
      ]
      if (node.alternate) {
        lines.push(`${indentation(indent)}else {`)
        lines.push(genBlock(node.alternate, indent + 1, topLevel))
        lines.push(`${indentation(indent)}}`)
      }
      return lines.filter((line) => line.length > 0).join("\n")
    }
    if (node instanceof core.SimmerStmt) {
      const body = genBlock(node.body, indent + 1, topLevel)
      return [
        `${indentation(indent)}while (${gen(node.condition)}) {`,
        body,
        `${indentation(indent)}}`,
      ]
        .filter((line) => line.length > 0)
        .join("\n")
    }
    if (node instanceof core.BatchStmt) {
      const body = genBlock(node.body, indent + 1, topLevel)
      return [
        `${indentation(indent)}for (const ${node.varName} of ${gen(node.collection)}) {`,
        body,
        `${indentation(indent)}}`,
      ]
        .filter((line) => line.length > 0)
        .join("\n")
    }
    if (node instanceof core.TossStmt) {
      return `${indentation(indent)}break;`
    }
    if (node instanceof core.SkipStmt) {
      return `${indentation(indent)}continue;`
    }
    if (node instanceof core.SpoiledStmt) {
      return `${indentation(indent)}throw new Error(${gen(node.message)});`
    }
    if (node instanceof core.BinaryExp) {
      if (node.op === "=") {
        return `${gen(node.left)} = ${gen(node.right)}`
      }
      if (node.op === "and") {
        return `(${gen(node.left)} && ${gen(node.right)})`
      }
      if (node.op === "or") {
        return `(${gen(node.left)} || ${gen(node.right)})`
      }
      if (node.op === "==") {
        return `(${gen(node.left)} === ${gen(node.right)})`
      }
      if (node.op === "!=") {
        return `(${gen(node.left)} !== ${gen(node.right)})`
      }
      return `(${gen(node.left)} ${node.op} ${gen(node.right)})`
    }
    if (node instanceof core.UnaryExp) {
      if (node.op === "not") {
        return `(!${gen(node.operand)})`
      }
      if (node.op === "-") {
        return `(-${gen(node.operand)})`
      }
    }
    if (node instanceof core.CallExp) {
      return `${gen(node.callee)}(${node.args.map((arg) => gen(arg)).join(", ")})`
    }
    if (node instanceof core.FieldAccessExp) {
      return `${gen(node.object)}.${node.field}`
    }
    if (node instanceof core.IndexAccessExp) {
      return `${gen(node.collection)}[${gen(node.index)}]`
    }
    if (node instanceof core.StructLit) {
      const fields = node.fields
        .map((field) => `${field.name}: ${gen(field.value)}`)
        .join(", ")
      return `({ ${fields} })`
    }
    if (node instanceof core.CollectionLit) {
      return `[${node.elements.map((element) => gen(element)).join(", ")}]`
    }
    if (node instanceof core.UnitLit) {
      return String(node.value)
    }
    if (node instanceof core.IntLit) {
      return String(node.value)
    }
    if (node instanceof core.FloatLit) {
      return String(node.value)
    }
    if (node instanceof core.StringLit) {
      return JSON.stringify(node.value)
    }
    if (node instanceof core.BoolLit) {
      return node.value ? "true" : "false"
    }
    if (node instanceof core.IdRef) {
      return node.name
    }
    throw new TypeError(`unknown node ${node.constructor.name}`)
  }

  return gen(program)
}
